In [1]:
# TODO: Add import statements
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

In [2]:
# Assign the data to predictor and outcome variables
# TODO: Load the data
train_data = pd.read_csv('data.csv', header = None)

X = train_data.iloc[:,:-1]
y = train_data.iloc[:,-1]

In [10]:
# TODO: Create the standardization scaling object.
scaler = StandardScaler()

# TODO: Fit the standardization parameters and scale the data.
X_scaled = scaler.fit_transform(X)
np.set_printoptions(suppress=True)
print((X_scaled))
# TODO: Create the linear regression model with lasso regularization.
lasso_reg = Lasso()

# TODO: Fit the model.
lasso_reg.fit(X_scaled, y)

# TODO: Retrieve and print out the coefficients from the regression model.
reg_coef = lasso_reg.coef_
reg_coef

[[ 0.2409391   1.29044717 -1.32657695  0.36275561 -1.2944825   1.07584269]
 [-0.68938564 -0.11204802  1.17210015  0.39065053 -1.07641127 -0.01839415]
 [ 0.93527173  0.67240746 -0.12889865  0.50294917  0.14243226 -1.18481222]
 [ 0.08434732 -1.66990046 -1.20523179  0.57451893  0.17702405 -0.44204755]
 [ 1.07073817  0.01281731  2.23374324  0.70775077  0.58935408  1.53832915]
 [-0.50354701 -0.38287779 -0.28670466 -0.135597   -0.73256722  2.81663911]
 [-1.26838661  0.06307229  1.29647329  1.3896517   0.0937563  -0.1109792 ]
 [-1.28336432  0.46855927 -0.6533687  -0.86017437 -0.8002199  -1.26209441]
 [ 1.58175014  1.31910564 -2.33513254 -0.9562893  -0.82997282 -0.53123196]
 [-1.07677452 -2.30532033  0.41981339 -0.66365667  0.67435473  0.91859071]
 [ 1.58184956  0.96246819 -0.33318345 -0.4412347   0.89885886  0.20994209]
 [ 0.80234857 -1.45547958 -0.99759825 -0.23403866  1.12826182 -0.48356821]
 [ 1.81633052 -0.2508811   0.46212847  0.12776559  1.84677602 -0.30004358]
 [-0.24750869  0.21096272

array([  0.        ,   3.90753617,   9.02575748,  -0.        ,
       -11.78303187,   0.45340137])